version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: jony_newtype
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_database
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./docker/postgres/script:/docker-entrypoint-initdb.d
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - '5432:5432'
    networks:
      - app-networks
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: jony_newtype@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_PREFERENCES_JSON_FILE: /pgadmin/preferences.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/postgres/servers.json:/pgadmin4/servers.json
      - ./docker/postgres/preferences.json:/pgadmin/preferences.json
    depends_on:
      - db
    networks:
      - app-networks

  nestjs:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/nest-api:/app
    ports:
      - '3000:3000'
    networks:
      - app-networks

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/next-front:/app
    ports:
      - '4000:3000'
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge

volumes:
  postgres_volume:
  pgadmin-data: