version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./docker/postgres/script:/docker-entrypoint-initdb.d
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - '5432:5432'
    networks:
      - app-networks
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_PREFERENCES_JSON_FILE: /pgadmin/preferences.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/postgres/servers.json:/pgadmin4/servers.json
      - ./docker/postgres/preferences.json:/pgadmin/preferences.json
    depends_on:
      - db
    networks:
      - app-networks
    env_file:
      - .env

  nestjs:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/nest-api:/app
      - nestjs_node_modules:/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - app-networks

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/next-front:/app
      - nextjs_node_modules:/app/node_modules
    ports:
      - '4000:3000'
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge

volumes:
  postgres_volume:
  pgadmin-data:
  nestjs_node_modules:
  nextjs_node_modules: